from __future__ import annotations
import json, hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parent
def write(name,obj): (ROOT/name).write_text(json.dumps(obj,indent=2)+'\n',encoding='utf-8')
def main():
 inv=json.loads((ROOT/'R5_17_B7_A3F2_P7Q_PRE5D_STATIC_COMPLETION_GAP_INVENTORY.json').read_text())
 matrix=[
  {'provider_id':'SHANGGUAN_DTB_2017','citation':'Shangguan et al. (2017), doi:10.1002/2016MS000686','provider_version':'2017 publication/product','provider_status':'RESEARCHED_NOT_ACQUIRED','current_access_status':'paper open access; payload endpoint not locally acquired','license':'CC BY-NC-ND 4.0 per publisher','spatial_resolution':'global raster product; exact payload grid must be verified at acquisition','spatial_extent':'global land prediction domain','temporal_semantics':'GEOLOGICAL_PRESENT','measured_or_modelled':'modelled spatial predictions','source_observations':'soil profiles, borehole logs, expert pseudo-observations','upstream_covariates':['topography/slope','remote sensing','GLiM lithology','climate/land-surface covariates'],'dependency_on_other_candidates':'GLiM and topographic covariates; Pelletier comparison reported, independence must not be assumed','bedrock_exposed_support':'CONDITIONAL','residual_regolith_support':'INSUFFICIENT','saprolite_support':'INSUFFICIENT','thickness_support':'DIRECT_STRUCTURAL_EVIDENCE','lithology_support':'LITHOLOGY_CONDITIONER','direct_or_derived_authority':'DERIVED_STRUCTURAL_EVIDENCE / EXPOSURE_LIKELIHOOD_EVIDENCE','main_uncertainties':['OBSERVATION_UNCERTAINTY','MODEL_PREDICTION_UNCERTAINTY','SPATIAL_AGGREGATION_UNCERTAINTY','PROVIDER_DEPENDENCY_UNCERTAINTY','EXTRAPOLATION_UNCERTAINTY'],'acquisition_size_if_known':'unknown until official payload endpoint is confirmed','acquisition_required':True,'runtime_required':False,'new_simulation_required':False,'recommended_arcana_role':'derived DTB/R-horizon evidence; no automatic exposure threshold','scientific_ceiling':'cannot alone establish canonical material branch, residual regolith, or saprolite'},
  {'provider_id':'PELLETIER_ORNL_DAAC_1304','citation':'Pelletier et al. (2016), doi:10.1002/2015MS000526; ORNL DAAC 1304 doi:10.3334/ORNLDAAC/1304','provider_version':'2016 / DAAC 1304','provider_status':'PUBLICLY_CATALOGUED_NOT_ACQUIRED','current_access_status':'public catalog and protected bundle endpoint; payload not locally acquired','license':'US Government work / DAAC terms; verify bundle terms','spatial_resolution':'30 arcsec (~1 km)','spatial_extent':'global, catalog metadata south to -60 degrees','temporal_semantics':'GEOLOGICAL_PRESENT','measured_or_modelled':'modelled thickness estimates','source_observations':'geomorphic models calibrated with high-resolution regional data','upstream_covariates':['topography','climate','geology','landform type'],'dependency_on_other_candidates':'shares covariate domains with Shangguan; not independent evidence vote','bedrock_exposed_support':'CONDITIONAL','residual_regolith_support':'CONDITIONAL','saprolite_support':'INSUFFICIENT','thickness_support':'THICKNESS_EVIDENCE','lithology_support':'none as class authority','direct_or_derived_authority':'DERIVED_STRUCTURAL_EVIDENCE','main_uncertainties':['MODEL_PREDICTION_UNCERTAINTY','SPATIAL_AGGREGATION_UNCERTAINTY','EXTRAPOLATION_UNCERTAINTY'],'acquisition_size_if_known':'bundle size not established in local authority','acquisition_required':True,'runtime_required':False,'new_simulation_required':False,'recommended_arcana_role':'primary structural thickness evidence; conservative weathered/regolith thickness only','scientific_ceiling':'intact regolith is not equivalent to saprolite or residual class identity'},
  {'provider_id':'GLIM_V1','citation':'Hartmann & Moosdorf (2012), doi:10.1029/2012GC004370; dataset doi:10.1594/PANGAEA.788537','provider_version':'v1.0','provider_status':'LOCALLY_CACHED_CONDITIONER','current_access_status':'locally acquired prior authority','license':'dataset terms; preserve citation','spatial_resolution':'0.5 degree gridded product; source maps target scale 1:1,000,000','spatial_extent':'global mapped surface domain','temporal_semantics':'MODERN_ENDPOINT','measured_or_modelled':'assembled/translated surface lithology map','source_observations':'92 regional lithological maps and regional literature','upstream_covariates':[],'dependency_on_other_candidates':'not a substrate exposure classifier','bedrock_exposed_support':'INSUFFICIENT','residual_regolith_support':'INSUFFICIENT','saprolite_support':'INSUFFICIENT','thickness_support':'none','lithology_support':'LITHOLOGY_CONDITIONER','direct_or_derived_authority':'LITHOLOGY_CONDITIONER','main_uncertainties':['SEMANTIC_MAPPING_UNCERTAINTY','SPATIAL_AGGREGATION_UNCERTAINTY'],'acquisition_size_if_known':'local cache already present','acquisition_required':False,'runtime_required':False,'new_simulation_required':False,'recommended_arcana_role':'surface lithology conditioner after substrate eligibility/classifier gate','scientific_ceiling':'must not replace GUM, infer exposure, depth, regolith, or saprolite'}]
 graph={'stage':'R5.17-B7-A3F2-P7Q-PRE5E','nodes':['raw observations','topography/climate/geology covariates','GLiM','Pelletier','Shangguan DTB','future ARCANA classifier'],'edges':['raw observations -> Shangguan','topography/climate/geology covariates -> Pelletier','topography/remote sensing/GLiM -> Shangguan','Pelletier -> comparison/related structural evidence','Shangguan + Pelletier + GLiM -> dependency-aware future classifier'],'independence_rule':'Do not count dependent providers as independent evidence votes.'}
 feas={'stage':'R5.17-B7-A3F2-P7Q-PRE5E','direct_target_cells':50568,'unknown_material_upper_bound':64579,'single_provider_sufficient':False,'composite_provider_classifier_feasible':'DEPENDENCY_AWARE_COMPOSITE_CLASSIFIER_FEASIBLE','source_contract_only':['structural thickness evidence','DTB/R-horizon likelihood evidence','GLiM lithology conditioner','ARCANA process/land eligibility'],'bedrock_exposed':'CONDITIONAL','residual_regolith':'CONDITIONAL','saprolite':'INSUFFICIENT','thresholds_defined':False,'transported_material_preemption':'GUM-supported transported branch outranks any future classifier.'}
 acq={'stage':'R5.17-B7-A3F2-P7Q-PRE5E','acquisition_required':True,'bundle':['SHANGGUAN_DTB_2017','PELLETIER_ORNL_DAAC_1304'],'required_files':['official DTB absolute/censored/R-horizon payloads and metadata','ORNL DAAC 1304 soil thickness, intact-regolith thickness, sedimentary-deposit thickness and metadata'],'hashing':'SHA256 all acquired files; preserve archive and extracted-file hashes','no_acquisition_performed':True,'next_gate':'AUTHORIZE_P7Q_PRE5F_ACQUIRE_AND_VALIDATE_SUBSTRATE_PROVIDER_BUNDLE'}
 adj={'stage':'R5.17-B7-A3F2-P7Q-PRE5E','classification':'NONCANONICAL_PROVIDER_RESEARCH_AND_FEASIBILITY_ADJUDICATION','decision':'AUTHORIZE_P7Q_PRE5F_ACQUIRE_AND_VALIDATE_SUBSTRATE_PROVIDER_BUNDLE','verdict':'PASS_P7Q_PRE5E_RESIDUAL_BEDROCK_PROVIDER_FEASIBILITY_ADJUDICATED','direct_target_cells':50568,'providers_researched':3,'no_classification':True,'no_payload_acquired':True,'no_materialization':True,'canonical_maturity':'L1_SOURCE_BOUND_PARTIAL','prototype_maturity':'L2_STATIC_STATE_CANDIDATE_PARTIAL','p7q_reopened':False,'sources':['https://doi.org/10.1002/2016MS000686','https://doi.org/10.3334/ORNLDAAC/1304','https://doi.org/10.1029/2012GC004370']}
 write('R5_17_B7_A3F2_P7Q_PRE5E_PROVIDER_EVIDENCE_MATRIX.json',matrix); write('R5_17_B7_A3F2_P7Q_PRE5E_PROVIDER_DEPENDENCY_GRAPH.json',graph); write('R5_17_B7_A3F2_P7Q_PRE5E_CLASS_FEASIBILITY_MATRIX.json',feas); write('R5_17_B7_A3F2_P7Q_PRE5E_ACQUISITION_PLAN.json',acq); write('R5_17_B7_A3F2_P7Q_PRE5E_ADJUDICATION.json',adj)
 (ROOT/'R5_17_B7_A3F2_P7Q_PRE5E_ADJUDICATION.md').write_text('# R5.17-B7-A3F2-P7Q-PRE5E\n\nProvider research finds no single sufficient authority. Shangguan supplies conditional derived depth-to-bedrock/R-horizon evidence; Pelletier supplies conditional structural thickness evidence; GLiM remains a surface lithology conditioner. Their dependencies prohibit independent-vote confidence multiplication.\n\nDecision: `AUTHORIZE_P7Q_PRE5F_ACQUIRE_AND_VALIDATE_SUBSTRATE_PROVIDER_BUNDLE`\n\nVerdict: `PASS_P7Q_PRE5E_RESIDUAL_BEDROCK_PROVIDER_FEASIBILITY_ADJUDICATED`\n\nNo thresholds, classification, payload acquisition, simulation, soil, parent material, or temporal reconstruction was performed. P7Q remains suspended. Sources: https://doi.org/10.1002/2016MS000686 ; https://doi.org/10.3334/ORNLDAAC/1304 ; https://doi.org/10.1029/2012GC004370\n',encoding='utf-8')
 print(json.dumps(adj,indent=2))
if __name__=='__main__': main()
