from pathlib import Path
import argparse,json,numpy as np,sys
from arcana_worldsim.scientific_engines.r334_producer_domestication import *
from arcana_worldsim.scientific_engines.r334_producer_domestication import _close_manifest
p=argparse.ArgumentParser();p.add_argument('--root',required=True);a=p.parse_args();root=Path(a.root);out=root/'outputs'/'v0_6D1_R3_34';seal=root/'outputs'/'v0_6D1_R3_34_SEAL';seal.mkdir(parents=True,exist_ok=True);checks=[]
def ck(n,c,d=None): checks.append({'name':n,'pass':bool(c),'detail':d})
try:
 inp=validate_inputs(root);_close_manifest(out,'R3_34_OUTPUT_MANIFEST.json'); audit=load_json(out/'R3_34_INTEGRATED_AUDIT.json'); auth=load_json(out/'R3_34_PRODUCER_OPERATIONAL_TAXON_AUTHORITY.json'); reg=load_json(out/'R3_34_PRODUCER_TAXON_REGISTRY.json'); outs=load_json(out/'R3_34_DOMESTICATION_FOOD_PRODUCTION_REASSESSMENT.json'); sens=load_json(out/'R3_34_SENSITIVITY_AND_ROBUSTNESS.json'); cp=load_json(out/'R3_34_FOOD_PRODUCTION_CHECKPOINT.json'); land=np.load(out/'R3_34_PRODUCER_RESOURCE_LANDSCAPE.npz',allow_pickle=False); z=np.load(out/'R3_34_PLANT_COEVOLUTION_DOMESTICATION_TRAJECTORIES.npz',allow_pickle=False)
 ck('parent_authority_validate',inp['a33']['status']==PARENT_PASS);ck('output_manifest_closure',True);ck('integrated_audit_all_pass',audit['checks_failed']==0,[audit['checks_passed'],audit['checks_total']]);ck('producer_registry_36',reg['taxon_count']==36);ck('producer_archetypes_6',len(reg['archetypes'])==6);ck('no_retroactive_phylogeny',auth['retroactive_h0_flora_phylogeny_claimed'] is False);ck('taxonomic_claim_explicit','NO_NAMED' in auth['taxonomic_claim']);ck('parent_environment_hash_exact',auth['parent_hashes']['r333_environment_sha256']==sha256_file(inp['r33']/'R3_33_HOLOCENE_ENVIRONMENTAL_RESOURCE_LANDSCAPE.npz'));ck('candidate_order_exact',list(map(str,z['candidate_ids']))==EXPECTED_CANDIDATES);ck('member_mapping_exact',np.array_equal(z['parent_member_indices'],inp['z32']['parent_member_indices']));ck('landscape_keys_exact',set(land.files)=={'anchor_age_ka','producer_taxon_ids','landscape_variable_names','producer_landscape'});ck('landscape_geometry',land['producer_landscape'].shape==(36,9,90,180,4));ck('landscape_bounds',np.isfinite(land['producer_landscape']).all() and land['producer_landscape'].min()>=0 and land['producer_landscape'].max()<=1);ck('trajectory_keys_exact',set(z.files)=={'candidate_ids','parent_member_indices','producer_taxon_ids','age_ka','anchor_age_ka','trajectory_variable_names','trajectory_state','domestication_stage','anchor_group_overlap'});ck('trajectory_geometry',z['trajectory_state'].shape==(32,2,36,145,10));ck('trajectory_bounded',np.isfinite(z['trajectory_state']).all() and z['trajectory_state'].min()>=0 and z['trajectory_state'].max()<=1);ck('stage_bounded',set(np.unique(z['domestication_stage'])).issubset(set(range(6))));ck('initial_propagation_divergence_zero',np.max(z['trajectory_state'][:,:,:,0,3:6])==0);ck('sensitivity_9',sens['variant_count']==9);ck('sensitivity_no_selection',sens['selection_gate'] is False);ck('checkpoint_semantics',cp['producer_operational_taxon_authority_materialized'] is True and cp['retroactive_h0_flora_phylogeny_claimed'] is False);ck('agriculture_rule_consistent',(not cp['agriculture_materialized']) or len(cp['materialized_functional_plant_domesticates'])>=1);ck('no_unique_human_identity',cp['unique_human_identity_materialized'] is False);ck('deep_off',cp['deep_biological_coupling'] is False);ck('evidence_multisource',len(auth['evidence_basis'])>=8)
except Exception as e: ck('audit_exception',False,repr(e))
failed=[x for x in checks if not x['pass']]; status=FINAL_PASS if not failed else 'FAIL_R334_FINAL_SEAL_AUDIT'; nxt='FOOD_PRODUCTION_DEMOGRAPHIC_TRANSITION_AND_SETTLEMENT_ECONOMY' if (not failed and cp.get('plant_food_production_emergence')) else 'PRODUCER_HERITABLE_VARIATION_SELECTION_RESPONSE_AND_DOMESTICATION_GENETICS'
res={'stage':STAGE,'audit':'FINAL_SINGLE_STAGE_PRODUCER_OPERATIONAL_TAXON_PLANT_COEVOLUTION_DOMESTICATION_AND_FOOD_PRODUCTION_AUTHORITY_CLOSURE','status':status,'verdict':'SEALED' if not failed else 'FAIL','checks_passed':len(checks)-len(failed),'checks_total':len(checks),'checks_failed':len(failed),'summary':{'producer_operational_taxa':36,'materialized_functional_plant_domesticates':cp.get('materialized_functional_plant_domesticates',[]),'incipient_plant_domestication_taxa':cp.get('incipient_plant_domestication_taxa',[]),'plant_food_production_emergence':cp.get('plant_food_production_emergence',False),'agriculture_materialized':cp.get('agriculture_materialized',False),'unique_human_identity_materialized':False,'deep_biological_coupling':False,'next_stage':nxt},'checks':checks};write_json(seal/'R3_34_FINAL_SEAL_AUDIT.json',res);(seal/'R3_34_FINAL_SEAL_AUDIT.md').write_text(f"# R3.34 Final Seal\n\n- Status: `{status}`\n- Checks: **{res['checks_passed']}/{res['checks_total']}**\n",encoding='utf-8');files={}
for n in ['R3_34_FINAL_SEAL_AUDIT.json','R3_34_FINAL_SEAL_AUDIT.md']:
 q=seal/n;files[n]={'bytes':q.stat().st_size,'sha256':sha256_file(q)}
write_json(seal/'R3_34_FINAL_SEAL_MANIFEST.json',{'stage':STAGE,'status':status,'files':files});print(json.dumps(res,indent=2));sys.exit(1 if failed else 0)
