from pathlib import Path
import argparse,json,numpy as np,sys
from arcana_worldsim.scientific_engines.r335_producer_genetics import *
from arcana_worldsim.scientific_engines.r335_producer_genetics import _close_manifest
p=argparse.ArgumentParser();p.add_argument('--root',required=True);a=p.parse_args();root=Path(a.root);out=root/'outputs'/'v0_6D1_R3_35';seal=root/'outputs'/'v0_6D1_R3_35_SEAL';seal.mkdir(parents=True,exist_ok=True);checks=[]
def ck(n,c,d=None):checks.append({'name':n,'pass':bool(c),'detail':d})
try:
 inp=validate_inputs(root);_close_manifest(out,'R3_35_OUTPUT_MANIFEST.json');audit=load_json(out/'R3_35_INTEGRATED_AUDIT.json');auth=load_json(out/'R3_35_PRODUCER_QUANTITATIVE_GENETICS_AUTHORITY.json');outs=load_json(out/'R3_35_DOMESTICATION_GENETICS_OUTCOMES.json');sens=load_json(out/'R3_35_SENSITIVITY_AND_ROBUSTNESS.json');cp=load_json(out/'R3_35_FOOD_PRODUCTION_CHECKPOINT.json');pri=np.load(out/'R3_35_PRODUCER_GENETIC_PRIORS.npz',allow_pickle=False);z=np.load(out/'R3_35_PRODUCER_DOMESTICATION_GENETIC_REPLAY.npz',allow_pickle=False);cfg=load_json(root/'configs/world1_r335_producer_genetics_v0_6D1_R3_35.json')
 ck('parent_authority_validate',inp['a34']['status']==PARENT_PASS);ck('output_manifest_closure',True);ck('integrated_audit_all_pass',audit['checks_failed']==0,[audit['checks_passed'],audit['checks_total']]);ck('producer_count_36',auth['producer_taxon_count']==36);ck('genetic_traits_6',len(auth['genetic_trait_names'])==6);ck('r334_thresholds_inherited',auth['r334_domestication_thresholds_inherited_exactly'] is True);ck('no_retroactive_phylogeny',auth['retroactive_h0_flora_phylogeny_claimed'] is False);ck('parent_hash_exact',auth['parent_hashes']['r334_trajectory_sha256']==sha256_file(inp['r34']/'R3_34_PLANT_COEVOLUTION_DOMESTICATION_TRAJECTORIES.npz'));ck('prior_keys_exact',set(pri.files)=={'producer_taxon_ids','genetic_trait_names','initial_additive_variance','environmental_variance','initial_heritability','selection_profile','generation_interval_years'});ck('prior_geometry',pri['initial_additive_variance'].shape==(36,6));ck('prior_va_positive',pri['initial_additive_variance'].min()>0);ck('replay_keys_exact',set(z.files)=={'candidate_ids','parent_member_indices','producer_taxon_ids','age_ka','genetic_trait_names','managed_mean_shift','additive_variance','effective_heritability','selection_response','effective_propagation_control','effective_dependency','genetic_divergence_index','effective_plant_food_contribution','genetic_domestication_index','domestication_stage'});ck('candidate_order_exact',list(map(str,z['candidate_ids']))==EXPECTED_CANDIDATES);ck('member_mapping_exact',np.array_equal(z['parent_member_indices'],inp['z34']['parent_member_indices']));ck('time_axis_exact',np.array_equal(z['age_ka'],inp['z34']['age_ka']));ck('genetic_geometry',z['managed_mean_shift'].shape==(32,2,36,145,6));ck('genetic_numeric_finite',np.isfinite(z['managed_mean_shift']).all() and np.isfinite(z['additive_variance']).all());ck('genetic_mean_bounded',z['managed_mean_shift'].min()>=0 and z['managed_mean_shift'].max()<=1);ck('va_positive_bounded',z['additive_variance'].min()>0 and z['additive_variance'].max()<=float(cfg['va_ceiling'])+1e-7);ck('heritability_bounded',z['effective_heritability'].min()>=0 and z['effective_heritability'].max()<=1);ck('initial_wild_reference_zero',np.max(z['managed_mean_shift'][:,:,:,0,:])==0);ck('propagation_not_below_parent',np.min(z['effective_propagation_control']-np.asarray(inp['z34']['trajectory_state'],float)[...,3])>=-1e-6);ck('stage_bounded',set(np.unique(z['domestication_stage'])).issubset(set(range(6))));ck('sensitivity_12',sens['variant_count']==12);ck('sensitivity_no_selection',sens['selection_gate'] is False);ck('checkpoint_agriculture_rule',(not cp['agriculture_materialized']) or len(cp['materialized_functional_plant_domesticates'])>=1);ck('no_unique_human_identity',cp['unique_human_identity_materialized'] is False);ck('deep_off',cp['deep_biological_coupling'] is False);ck('evidence_multisource',len(auth['evidence_basis'])>=6)
except Exception as e:ck('audit_exception',False,repr(e))
failed=[x for x in checks if not x['pass']];status=FINAL_PASS if not failed else 'FAIL_R335_FINAL_SEAL_AUDIT';nxt='FOOD_PRODUCTION_DEMOGRAPHIC_TRANSITION_AND_SETTLEMENT_ECONOMY' if (not failed and cp.get('plant_food_production_emergence')) else 'PRODUCER_DOMESTICATION_SELECTION_ECOLOGY_REASSESSMENT_OR_FORAGER_PATHWAY'
res={'stage':STAGE,'audit':'FINAL_SINGLE_STAGE_PRODUCER_HERITABLE_VARIATION_SELECTION_RESPONSE_AND_DOMESTICATION_GENETICS_AUTHORITY_CLOSURE','status':status,'verdict':'SEALED' if not failed else 'FAIL','checks_passed':len(checks)-len(failed),'checks_total':len(checks),'checks_failed':len(failed),'summary':{'producer_operational_taxa':36,'genetic_traits':6,'materialized_functional_plant_domesticates':cp.get('materialized_functional_plant_domesticates',[]),'incipient_plant_domestication_taxa':cp.get('incipient_plant_domestication_taxa',[]),'plant_food_production_emergence':cp.get('plant_food_production_emergence',False),'agriculture_materialized':cp.get('agriculture_materialized',False),'unique_human_identity_materialized':False,'deep_biological_coupling':False,'next_stage':nxt},'checks':checks};write_json(seal/'R3_35_FINAL_SEAL_AUDIT.json',res);(seal/'R3_35_FINAL_SEAL_AUDIT.md').write_text(f"# R3.35 Final Seal\n\n- Status: `{status}`\n- Checks: **{res['checks_passed']}/{res['checks_total']}**\n",encoding='utf-8');files={}
for n in ['R3_35_FINAL_SEAL_AUDIT.json','R3_35_FINAL_SEAL_AUDIT.md']:
 q=seal/n;files[n]={'bytes':q.stat().st_size,'sha256':sha256_file(q)}
write_json(seal/'R3_35_FINAL_SEAL_MANIFEST.json',{'stage':STAGE,'status':status,'files':files});print(json.dumps(res,indent=2));sys.exit(1 if failed else 0)
