from pathlib import Path
import argparse,json,numpy as np,sys
from arcana_worldsim.scientific_engines.r331_cultural_technological_ecology import *
from arcana_worldsim.scientific_engines.r331_cultural_technological_ecology import _close_manifest
p=argparse.ArgumentParser();p.add_argument('--root',required=True);a=p.parse_args();root=Path(a.root);out=root/'outputs'/'v0_6D1_R3_31';seal=root/'outputs'/'v0_6D1_R3_31_SEAL';seal.mkdir(parents=True,exist_ok=True);checks=[]
def ck(n,c,d=None):checks.append({'name':n,'pass':bool(c),'detail':d})
try:
 inp=validate_inputs(root);cfg=load_json(root/'configs/world1_r331_cultural_technological_ecology_v0_6D1_R3_31.json');_close_manifest(out,'R3_31_OUTPUT_MANIFEST.json');audit=load_json(out/'R3_31_INTEGRATED_AUDIT.json');auth=load_json(out/'R3_31_CULTURAL_TECHNOLOGICAL_ECOLOGY_AUTHORITY.json');outs=load_json(out/'R3_31_LINEAGE_TECHNOLOGICAL_ECOLOGY_OUTCOMES.json');sens=load_json(out/'R3_31_SENSITIVITY_AND_ROBUSTNESS.json');cp=load_json(out/'R3_31_CULTURAL_TECHNOLOGICAL_ECOLOGY_CHECKPOINT.json');z=np.load(out/'R3_31_CULTURAL_TECHNOLOGICAL_ECOLOGY_REPLAY.npz',allow_pickle=False);g=np.load(out/'R3_31_GROUP_TECHNOLOGICAL_ECOLOGY_ANCHORS.npz',allow_pickle=False)
 ck('parent_authority_validate',inp['a30']['status']==PARENT_PASS);ck('output_manifest_closure',True);ck('integrated_audit_all_pass',audit['checks_failed']==0 and audit['checks_passed']==audit['checks_total'],[audit['checks_passed'],audit['checks_total']]);ck('candidate_order_exact',list(map(str,z['candidate_ids']))==EXPECTED_CANDIDATES);ck('parent_member_mapping_exact',np.array_equal(z['parent_member_indices'],inp['z30']['parent_member_indices']));ck('time_axis_exact',np.array_equal(z['age_ka'],inp['z30']['age_ka']));ck('npz_keys_exact',set(z.files)=={'candidate_ids','parent_member_indices','age_ka','technology_domain_names','technology_domain_stock','ecology_variable_names','cultural_technological_ecology'});ck('domain_names_exact',list(map(str,z['technology_domain_names']))==TECH_NAMES);ck('ecology_names_exact',list(map(str,z['ecology_variable_names']))==ECO_NAMES);ck('domain_geometry',z['technology_domain_stock'].shape==(32,2,175,8));ck('ecology_geometry',z['cultural_technological_ecology'].shape==(32,2,175,10));ck('all_numeric_finite',np.isfinite(z['technology_domain_stock']).all() and np.isfinite(z['cultural_technological_ecology']).all() and np.isfinite(g['group_state']).all());ck('domain_stock_bounded',np.min(z['technology_domain_stock'])>=0 and np.max(z['technology_domain_stock'])<=1);ck('group_keys_exact',set(g.files)=={'candidate_ids','parent_member_indices','anchor_age_ka','group_variable_names','group_state','group_active'});ck('group_anchor_axis_exact',np.array_equal(g['anchor_age_ka'],inp['g30']['anchor_age_ka']));ck('group_geometry',g['group_state'].shape==(32,2,11,48,8));ck('group_active_exact_parent',np.array_equal(g['group_active'],inp['g30']['agent_active']));ck('represented_people_exact_parent',np.max(np.abs(g['group_state'][...,0]-inp['g30']['agent_state'][...,0]))<1e-10);ck('represented_camps_exact_parent',np.max(np.abs(g['group_state'][...,1]-inp['g30']['agent_state'][...,1]))<1e-10);ck('sensitivity_25',sens['variant_count']==25);ck('sensitivity_no_selection',sens['selection_gate'] is False);ck('both_lineages_retained',sens['candidate_retention']==EXPECTED_CANDIDATES);ck('authority_abstract_technology',auth['technology_semantics'].startswith('ABSTRACT_'));ck('no_specific_artifacts',auth['specific_artifact_materialized'] is False and cp['specific_artifact_materialized'] is False);ck('no_named_culture_language_religion',auth['named_culture_materialized'] is False and auth['language_materialized'] is False and auth['religion_materialized'] is False);ck('no_agriculture_city_state',auth['agriculture_materialized'] is False and auth['city_state_materialized'] is False);ck('no_unique_human_identity',auth['unique_human_identity_materialized'] is False and cp['unique_human_identity_materialized'] is False);ck('deep_off',auth['deep_biological_coupling'] is False);ck('evidence_multisource',len(auth['evidence_basis'])>=8)
except Exception as e:ck('audit_exception',False,repr(e))
failed=[x for x in checks if not x['pass']];status=FINAL_PASS if not failed else 'FAIL_R331_FINAL_SEAL_AUDIT';res={'stage':STAGE,'audit':'FINAL_SINGLE_STAGE_LATE_PLEISTOCENE_TO_HOLOCENE_CULTURAL_TECHNOLOGICAL_ECOLOGY_AUTHORITY_CLOSURE','status':status,'verdict':'SEALED' if not failed else 'FAIL','checks_passed':len(checks)-len(failed),'checks_total':len(checks),'checks_failed':len(failed),'summary':{'candidate_lineages':2,'technology_domains':8,'named_culture_materialized':False,'specific_artifact_materialized':False,'language_religion_agriculture_city_materialized':False,'unique_human_identity_materialized':False,'deep_biological_coupling':False,'next_stage':'SUBSISTENCE_INTENSIFICATION_REGIONAL_CULTURAL_LINEAGES_AND_EARLY_HOLOCENE_TRANSITIONS'},'checks':checks};write_json(seal/'R3_31_FINAL_SEAL_AUDIT.json',res);(seal/'R3_31_FINAL_SEAL_AUDIT.md').write_text(f"# R3.31 Final Seal\n\n- Status: `{status}`\n- Checks: **{res['checks_passed']}/{res['checks_total']}**\n",encoding='utf-8');files={};
for n in ['R3_31_FINAL_SEAL_AUDIT.json','R3_31_FINAL_SEAL_AUDIT.md']:
 q=seal/n;files[n]={'bytes':q.stat().st_size,'sha256':sha256_file(q)}
write_json(seal/'R3_31_FINAL_SEAL_MANIFEST.json',{'stage':STAGE,'status':status,'files':files});print(json.dumps(res,indent=2));sys.exit(1 if failed else 0)
