from pathlib import Path
import argparse,json,numpy as np,sys
from arcana_worldsim.scientific_engines.r336_producer_selection_ecology import *
from arcana_worldsim.scientific_engines.r336_producer_selection_ecology import _close_manifest
p=argparse.ArgumentParser();p.add_argument('--root',required=True);a=p.parse_args();root=Path(a.root);out=root/'outputs'/'v0_6D1_R3_36';seal=root/'outputs'/'v0_6D1_R3_36_SEAL';seal.mkdir(parents=True,exist_ok=True);checks=[]
def ck(n,c,d=None): checks.append({'name':n,'pass':bool(c),'detail':d})
try:
 inp=validate_inputs(root);_close_manifest(out,'R3_36_OUTPUT_MANIFEST.json');audit=load_json(out/'R3_36_INTEGRATED_AUDIT.json');auth=load_json(out/'R3_36_PRODUCER_SELECTION_ECOLOGY_AUTHORITY.json');outs=load_json(out/'R3_36_PATHWAY_OUTCOMES.json');sens=load_json(out/'R3_36_SENSITIVITY_AND_ROBUSTNESS.json');cp=load_json(out/'R3_36_PATHWAY_RESOLUTION_CHECKPOINT.json');eco=np.load(out/'R3_36_RESOURCE_SELECTION_ECOLOGY.npz',allow_pickle=False);z=np.load(out/'R3_36_DOMESTICATION_SELECTION_ECOLOGY_REPLAY.npz',allow_pickle=False);cfg=load_json(root/'configs/world1_r336_producer_selection_ecology_v0_6D1_R3_36.json')
 ck('parent_authority_validate',inp['a35']['status']==PARENT_PASS);ck('output_manifest_closure',True);ck('integrated_audit_all_pass',audit['checks_failed']==0,[audit['checks_passed'],audit['checks_total']]);ck('producer_count_36',auth['producer_taxon_count']==36);ck('r334_r335_gates_inherited',auth['r334_r335_domestication_gates_inherited_exactly'] is True);ck('r335_parent_hash_exact',auth['parent_hashes']['r335_replay_sha256']==sha256_file(inp['r35']/'R3_35_PRODUCER_DOMESTICATION_GENETIC_REPLAY.npz'));ck('r334_landscape_hash_exact',auth['parent_hashes']['r334_landscape_sha256']==sha256_file(inp['r34']/'R3_34_PRODUCER_RESOURCE_LANDSCAPE.npz'));ck('resource_semantics_explicit','R3_34_SEALED_90x180' in auth['resource_semantics']);ck('pathway_semantics_explicit',auth['pathway_resolution_semantics'].startswith('FOOD_PRODUCTION'))
 ck('ecology_keys_exact',set(eco.files)=={'anchor_age_ka','producer_taxon_ids','resource_concentration_anchor','resource_persistence_anchor','propagation_opportunity_anchor','resource_concentration_time','resource_persistence_time','propagation_opportunity_time'});ck('ecology_anchor_geometry',eco['resource_concentration_anchor'].shape==(36,9));ck('ecology_time_geometry',eco['resource_concentration_time'].shape==(36,145));ck('ecology_bounded',eco['resource_concentration_time'].min()>=0 and eco['resource_concentration_time'].max()<=1 and eco['resource_persistence_time'].min()>=0 and eco['resource_persistence_time'].max()<=1)
 expected={'candidate_ids','parent_member_indices','producer_taxon_ids','age_ka','genetic_trait_names','managed_mean_shift','additive_variance','effective_heritability','selection_response','effective_propagation_control','effective_dependency','genetic_divergence_index','effective_plant_food_contribution','genetic_domestication_index','managed_patch_persistence','managed_population_isolation','effective_wild_gene_flow','demographic_return_feedback','resource_concentration','resource_persistence','domestication_stage'}
 ck('replay_keys_exact',set(z.files)==expected);ck('candidate_order_exact',list(map(str,z['candidate_ids']))==EXPECTED_CANDIDATES);ck('member_mapping_exact',np.array_equal(z['parent_member_indices'],inp['z35']['parent_member_indices']));ck('time_axis_exact',np.array_equal(z['age_ka'],inp['z35']['age_ka']));ck('genetic_geometry',z['managed_mean_shift'].shape==(32,2,36,145,6));ck('selection_ecology_geometry',z['managed_patch_persistence'].shape==(32,2,36,145) and z['managed_population_isolation'].shape==(32,2,36,145));ck('numeric_finite',all(np.isfinite(z[k]).all() for k in ['managed_mean_shift','additive_variance','effective_propagation_control','managed_patch_persistence','managed_population_isolation','effective_wild_gene_flow','genetic_domestication_index']));ck('selection_ecology_bounded',z['managed_patch_persistence'].min()>=0 and z['managed_patch_persistence'].max()<=1 and z['managed_population_isolation'].min()>=0 and z['managed_population_isolation'].max()<=1);ck('wild_gene_flow_not_increased',np.max(z['effective_wild_gene_flow']-np.asarray(inp['z34']['trajectory_state'],float)[...,6])<=1e-6);ck('propagation_not_below_r335',np.min(z['effective_propagation_control']-np.asarray(inp['z35']['effective_propagation_control'],float))>=-2e-4);ck('stage_bounded',set(np.unique(z['domestication_stage'])).issubset(set(range(6))));ck('sensitivity_12',sens['variant_count']==12);ck('sensitivity_no_selection',sens['selection_gate'] is False);ck('pathway_enum',cp['resolved_pathway'] in {'FOOD_PRODUCTION_DOMESTICATION_PATHWAY','PROTRACTED_INCIPIENT_DOMESTICATION_PATHWAY','INTENSIVE_MANAGED_FORAGER_PATHWAY','MIXED_FORAGING_MANAGEMENT_PATHWAY'});ck('checkpoint_agriculture_rule',(not cp['agriculture_materialized']) or len(cp['materialized_functional_plant_domesticates'])>=1);ck('thresholds_not_relaxed',cfg['governance']['no_domestication_threshold_relaxation'] is True);ck('no_unique_human_identity',cp['unique_human_identity_materialized'] is False);ck('deep_off',cp['deep_biological_coupling'] is False);ck('evidence_multisource',len(auth['evidence_basis'])>=7)
except Exception as e: ck('audit_exception',False,repr(e))
failed=[x for x in checks if not x['pass']];status=FINAL_PASS if not failed else 'FAIL_R336_FINAL_SEAL_AUDIT'
if not failed:
 if cp.get('resolved_pathway')=='FOOD_PRODUCTION_DOMESTICATION_PATHWAY': nxt='FOOD_PRODUCTION_DEMOGRAPHIC_TRANSITION_AND_SETTLEMENT_ECONOMY'
 elif cp.get('resolved_pathway')=='PROTRACTED_INCIPIENT_DOMESTICATION_PATHWAY': nxt='INCIPIENT_DOMESTICATION_LONG_HORIZON_AND_FOOD_PRODUCTION_TRANSITION'
 else: nxt='INTENSIVE_MANAGED_FORAGER_DEMOGRAPHY_SETTLEMENT_AND_EXCHANGE_ECONOMY'
else: nxt='R336_REPAIR_REQUIRED'
res={'stage':STAGE,'audit':'FINAL_SINGLE_STAGE_PRODUCER_DOMESTICATION_SELECTION_ECOLOGY_AND_PATHWAY_RESOLUTION_AUTHORITY_CLOSURE','status':status,'verdict':'SEALED' if not failed else 'FAIL','checks_passed':len(checks)-len(failed),'checks_total':len(checks),'checks_failed':len(failed),'summary':{'producer_operational_taxa':36,'materialized_functional_plant_domesticates':cp.get('materialized_functional_plant_domesticates',[]),'incipient_plant_domestication_taxa':cp.get('incipient_plant_domestication_taxa',[]),'plant_food_production_emergence':cp.get('plant_food_production_emergence',False),'agriculture_materialized':cp.get('agriculture_materialized',False),'resolved_pathway':cp.get('resolved_pathway'),'unique_human_identity_materialized':False,'deep_biological_coupling':False,'next_stage':nxt},'checks':checks};write_json(seal/'R3_36_FINAL_SEAL_AUDIT.json',res);(seal/'R3_36_FINAL_SEAL_AUDIT.md').write_text(f"# R3.36 Final Seal\n\n- Status: `{status}`\n- Checks: **{res['checks_passed']}/{res['checks_total']}**\n- Resolved pathway: **{cp.get('resolved_pathway')}**\n",encoding='utf-8');files={}
for n in ['R3_36_FINAL_SEAL_AUDIT.json','R3_36_FINAL_SEAL_AUDIT.md']:
 q=seal/n;files[n]={'bytes':q.stat().st_size,'sha256':sha256_file(q)}
write_json(seal/'R3_36_FINAL_SEAL_MANIFEST.json',{'stage':STAGE,'status':status,'files':files});print(json.dumps(res,indent=2));sys.exit(1 if failed else 0)
