"""Authorial B6I first-segment topology process scope and query semantics.

This module declares model scope only. It does not execute an event detector,
mutate topology, or perform a transition.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from types import MappingProxyType
from typing import Mapping


RIFT_ACTIVATION_HORIZON_YEARS = 27123.405156307464


class FirstSegmentStatus(str, Enum):
    ENABLED = "ENABLED"
    DERIVED_FROM_ENABLED_EVENT = "DERIVED_FROM_ENABLED_EVENT"
    OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL = "OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL"


class EventQueryStatus(str, Enum):
    EVENT_OCCURRED = "EVENT_OCCURRED"
    EVENT_DID_NOT_OCCUR = "EVENT_DID_NOT_OCCUR"
    MODEL_SCOPE_LIMITATION = "MODEL_SCOPE_LIMITATION"
    UNKNOWN = "UNKNOWN"


class UnknownTopologyEventError(KeyError):
    """Raised closed when a newly introduced topology event lacks authority."""


@dataclass(frozen=True)
class TopologyProcess:
    event_class: str
    first_segment_status: FirstSegmentStatus
    authority: str
    detector: str
    horizon_status: str
    future_extension_status: str
    derived_from: str | None = None


@dataclass(frozen=True)
class TopologyProcessRegistry:
    schema: str
    model_scope: str
    topology_hold_rule: str
    processes: Mapping[str, TopologyProcess]
    unknown_event_policy: str

    def get(self, event_class: str) -> TopologyProcess:
        try:
            return self.processes[event_class]
        except KeyError as exc:
            raise UnknownTopologyEventError(
                f"topology event class has no first-segment authority: {event_class}"
            ) from exc

    def classify_observation(self, event_class: str, occurred: bool | None) -> EventQueryStatus:
        process = self.get(event_class)
        if process.first_segment_status is FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL:
            return EventQueryStatus.MODEL_SCOPE_LIMITATION
        if occurred is None:
            return EventQueryStatus.UNKNOWN
        return EventQueryStatus.EVENT_OCCURRED if occurred else EventQueryStatus.EVENT_DID_NOT_OCCUR

    def topology_hold_applies(self, elapsed_years: float) -> bool:
        """True strictly before the qualified enabled-event horizon."""
        if elapsed_years < 0:
            raise ValueError("elapsed_years must be non-negative")
        return elapsed_years < RIFT_ACTIVATION_HORIZON_YEARS


def _process(event_class: str, status: FirstSegmentStatus, authority: str,
             detector: str, horizon: str, extension: str,
             derived_from: str | None = None) -> TopologyProcess:
    return TopologyProcess(event_class, status, authority, detector, horizon, extension, derived_from)


def build_first_segment_registry() -> TopologyProcessRegistry:
    """Return the frozen, deterministic B6I event registry."""
    rows = (
        _process("RIFT_PROCESS_ACTIVATION", FirstSegmentStatus.ENABLED,
                 "B6A Census V3 rift guard; B6D D1; B6I authorial first-segment scope",
                 "Qualified conditional RIFT_INITIATION predicate under fixed-T0 Euler rates",
                 "QUALIFIED_EVENT_BOUND_27123.405156307464_YEAR_PAIR_1:3",
                 "Explicit successor topology-transition stage required; transition is not implemented in B6I"),
        _process("RIFT_ACTIVATION_BOUNDARY_TOPOLOGY_TRANSITION", FirstSegmentStatus.DERIVED_FROM_ENABLED_EVENT,
                 "B6I authorial scope; conditional implication from enabled rift activation",
                 "Triggered only by RIFT_PROCESS_ACTIVATION; no independent detector",
                 "INHERITS_RIFT_ACTIVATION_HORIZON_CONDITIONALLY__COUNTED_ONCE",
                 "Explicit successor topology-transition stage required; no silent mutation",
                 "RIFT_PROCESS_ACTIVATION"),
        _process("BOUNDARY_BIRTH_NON_RIFT", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("BOUNDARY_DEATH", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("INTERFACE_SPLIT", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("INTERFACE_MERGE", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("JUNCTION_BIRTH", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("JUNCTION_DEATH", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("JUNCTION_CONNECTIVITY_CHANGE", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("PLATE_SUPPORT_SPLIT", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("PLATE_SUPPORT_MERGE", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope", "Not generated by this model",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "May be added only by a future governed model extension"),
        _process("OTHER_NON_RIFT_TOPOLOGY_MUTATION", FirstSegmentStatus.OUT_OF_SCOPE_FOR_FIRST_SEGMENT_MODEL,
                 "B6I authorial first-segment scope; D1 fail-closed unknown-event policy",
                 "Not generated by this model; unregistered classes fail closed",
                 "NOT_APPLICABLE_OUT_OF_SCOPE", "Requires explicit future model registration and qualification"),
    )
    mapping = {row.event_class: row for row in sorted(rows, key=lambda row: row.event_class)}
    if len(mapping) != len(rows):
        raise ValueError("duplicate topology event class in first-segment registry")
    return TopologyProcessRegistry(
        schema="R6_FIRST_SEGMENT_TOPOLOGY_PROCESS_REGISTRY_V1",
        model_scope="FIRST_SEGMENT_TOPOLOGY_PROCESS_SCOPE",
        topology_hold_rule="FIRST_SEGMENT_TOPOLOGY_HOLD_UNTIL_ENABLED_EVENT",
        processes=MappingProxyType(mapping),
        unknown_event_policy="FAIL_CLOSED__UNKNOWN_TOPOLOGY_EVENT_CLASS_REQUIRES_EXPLICIT_MODEL_AUTHORITY",
    )


FIRST_SEGMENT_REGISTRY = build_first_segment_registry()


def registry_as_dict(registry: TopologyProcessRegistry = FIRST_SEGMENT_REGISTRY) -> dict[str, object]:
    """Serialize the registry in deterministic event-class order."""
    return {
        "schema": registry.schema,
        "model_scope": registry.model_scope,
        "topology_hold_rule": registry.topology_hold_rule,
        "unknown_event_policy": registry.unknown_event_policy,
        "processes": [
            {
                "event_class": row.event_class,
                "first_segment_status": row.first_segment_status.value,
                "authority": row.authority,
                "detector": row.detector,
                "horizon_status": row.horizon_status,
                "future_extension_status": row.future_extension_status,
                "derived_from": row.derived_from,
            }
            for row in registry.processes.values()
        ],
    }
